name: train config

device: cuda

num workers : 8
batch size : 256
seed : 1
max epochs : 60
input size : 128
num ftrs : 32

learning rate : !!float 6e-2
momentum : 0.9
weight decay : !!float 5e-4

train data folder: './Views'
test data folder : './CloseViews'
benchmark data dolder : './BenchmarkViews'

weights filepath: './Weights/model_pretrained.pt'